// Code generated by templ DO NOT EDIT.

package main

import "html"
import "context"
import "io"

func renderPosts(ctx context.Context, w io.Writer, posts []Post) (err error) {
	for _, p := range posts {
		err = renderPost(ctx, w, p)
		if err != nil {
			return err
		}
	}
	return err
}

func renderPost(ctx context.Context, w io.Writer, post Post) (err error) {
	_, err = io.WriteString(w, "<div>")
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, html.EscapeString(post.Name))
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, "</div>")
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, "<div>")
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, html.EscapeString(post.Author))
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, "</div>")
	if err != nil {
		return err
	}
	return err
}

