# See documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  dir: cmd
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - 386
  - arm
  - arm64
  - amd64
  ignore:
  - goos: darwin
    goarch: 386
signs:
  - artifacts: checksum
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
