// Code generated by templ@(devel) DO NOT EDIT.

package testfor

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"

func render(items []string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		// For
		for _, item := range items {
			// Element (standard)
			_, err = io.WriteString(w, "<div>")
			if err != nil {
				return err
			}
			// StringExpression
			_, err = io.WriteString(w, templ.EscapeString(item))
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</div>")
			if err != nil {
				return err
			}
		}
		return err
	})
}

