// Code generated by templ DO NOT EDIT.

package testfor

import "html"
import "context"
import "io"

func render(ctx context.Context, w io.Writer, items []string) (err error) {
	for _, item := range items {
		_, err = io.WriteString(w, "<div>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, html.EscapeString(item))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</div>")
		if err != nil {
			return err
		}
	}
	return err
}

