// Code generated by templ DO NOT EDIT.

package iffalse

import "html"
import "context"
import "io"

func render(ctx context.Context, w io.Writer, d data) (err error) {
	_, err = io.WriteString(w, "   ")
	if err != nil {
		return err
	}
	if d.IsTrue() {
		_, err = io.WriteString(w, "      ")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, html.EscapeString("True"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\n   ")
		if err != nil {
			return err
		}
	} else {
		_, err = io.WriteString(w, "\n      ")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, html.EscapeString("False"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "\n   ")
		if err != nil {
			return err
		}
	}
	_, err = io.WriteString(w, "\n")
	if err != nil {
		return err
	}
	return err
}

