// Code generated by templ@(devel) DO NOT EDIT.

package elseif

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func render(d data) templ.Component {
	return templ.ComponentFunc(func(templCtx context.Context, templW io.Writer) (templErr error) {
		templBuffer, templIsBuffer := templW.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		templCtx = templ.InitializeContext(templCtx)
		templVar1 := templ.GetChildren(templCtx)
		if templVar1 == nil {
			templVar1 = templ.NopComponent
		}
		templCtx = templ.ClearChildren(templCtx)
		_, templErr = templBuffer.WriteString("<div>")
		if templErr != nil {
			return templErr
		}
		if d.IsTrue() {
			var templVar2 string = "True"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar2))
			if templErr != nil {
				return templErr
			}
		} else if !d.IsTrue() {
			var templVar3 string = "False"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar3))
			if templErr != nil {
				return templErr
			}
		} else {
			var templVar4 string = "Else"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar4))
			if templErr != nil {
				return templErr
			}
		}
		_, templErr = templBuffer.WriteString("</div><div>")
		if templErr != nil {
			return templErr
		}
		if 1 == 2 {
			var templVar5 string = "If"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar5))
			if templErr != nil {
				return templErr
			}
		} else if 1 == 1 {
			var templVar6 string = "ElseIf"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar6))
			if templErr != nil {
				return templErr
			}
		}
		_, templErr = templBuffer.WriteString("</div><div>")
		if templErr != nil {
			return templErr
		}
		if 1 == 2 {
			var templVar7 string = "If"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar7))
			if templErr != nil {
				return templErr
			}
		} else if 1 == 3 {
			var templVar8 string = "ElseIf"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar8))
			if templErr != nil {
				return templErr
			}
		} else if 1 == 4 {
			var templVar9 string = "ElseIf"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar9))
			if templErr != nil {
				return templErr
			}
		} else if 1 == 1 {
			var templVar10 string = "OK"
			_, templErr = templBuffer.WriteString(templ.EscapeString(templVar10))
			if templErr != nil {
				return templErr
			}
		}
		_, templErr = templBuffer.WriteString("</div>")
		if templErr != nil {
			return templErr
		}
		if !templIsBuffer {
			_, templErr = templBuffer.WriteTo(templW)
		}
		return templErr
	})
}
