// Code generated by templ@(devel) DO NOT EDIT.

package ifelse

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"

func render(d data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		ctx, _ = templ.RenderedScriptsFromContext(ctx)
		// If
		if d.IsTrue() {
			// StringExpression
			_, err = io.WriteString(w, templ.EscapeString("True"))
			if err != nil {
				return err
			}
		} else {
			// StringExpression
			_, err = io.WriteString(w, templ.EscapeString("False"))
			if err != nil {
				return err
			}
		}
		return err
	})
}

